# Generated by Django 4.1.7 on 2023-04-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
