# Generated by Django 4.1.7 on 2023-04-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0002_alter_class_course_alter_course_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enrolment',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_date',
            new_name='enrolment_date',
        ),
    ]
