# Generated by Django 4.1.7 on 2023-05-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_student',
            field=models.ForeignKey(blank=True, db_column='studentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.student'),
        ),
    ]
