# Generated by Django 4.1.7 on 2023-04-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0004_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
